### Used Car Price Prediction using Linear Regression

In [166]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn import linear_model

## 1. Loading Dataset

In [167]:
# df = pd.read_csv("dataset/used_car_data.csv")

df = pd.read_csv("dataset/used_car_data.csv", encoding="latin1")  # or "ISO-8859-1", "windows-1252"

In [168]:
df.head()

,Brand,Condition,Fuel,KMs Driven,Model,Price,Registered City,Transaction Type,Year
0,Toyota,Used,Diesel,1.0,Prado,2100000,Karachi,Cash,1997.0
1,Suzuki,Used,Petrol,100000.0,Bolan,380000,Karachi,Cash,2006.0
2,Suzuki,Used,CNG,12345.0,Bolan,340000,Karachi,Cash,1998.0
3,Suzuki,Used,Petrol,94000.0,Alto,535000,Karachi,Cash,2010.0
4,Toyota,Used,Petrol,100000.0,Corolla XLI,1430000,Karachi,Cash,2013.0

## 2. Dataset Info

In [169]:
df.columns

Index(['Brand', 'Condition', 'Fuel', 'KMs Driven', 'Model', 'Price',
       'Registered City', 'Transaction Type', 'Year'],
      dtype='object')

In [170]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24973 entries, 0 to 24972
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             22836 non-null  object
 1   Condition         22837 non-null  object
 2   Fuel              22528 non-null  object
 3   KMs Driven        22687 non-null  float64
 4   Model             22525 non-null  object
 5   Price             24973 non-null  int64
 6   Registered City   20337 non-null  object
 7   Transaction Type  22528 non-null  object
 8   Year              22689 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 1.7+ MB

In [171]:
df.shape

(24973, 9)

### Checking fro missing values

In [172]:
df.isnull().sum()

Brand               2137
Condition           2136
Fuel                2445
KMs Driven          2286
Model               2448
Price                  0
Registered City     4636
Transaction Type    2445
Year                2284
dtype: int64

#### Remove Colmuns spaces

In [173]:
df.columns = df.columns.str.replace(" ", "_", regex=False)

In [174]:
df.head(2)

,Brand,Condition,Fuel,KMs_Driven,Model,Price,Registered_City,Transaction_Type,Year
0,Toyota,Used,Diesel,1.0,Prado,2100000,Karachi,Cash,1997.0
1,Suzuki,Used,Petrol,100000.0,Bolan,380000,Karachi,Cash,2006.0

### Feature Selections

##### drop : Transaction Type

In [175]:
new_df = df.drop("Transaction_Type", axis="columns")

In [176]:
new_df.head(2)

,Brand,Condition,Fuel,KMs_Driven,Model,Price,Registered_City,Year
0,Toyota,Used,Diesel,1.0,Prado,2100000,Karachi,1997.0
1,Suzuki,Used,Petrol,100000.0,Bolan,380000,Karachi,2006.0

## Handling Missing Values

In [177]:
new_df.isnull().sum()

Brand              2137
Condition          2136
Fuel               2445
KMs_Driven         2286
Model              2448
Price                 0
Registered_City    4636
Year               2284
dtype: int64

In [178]:
new_df.dtypes

Brand               object
Condition           object
Fuel                object
KMs_Driven         float64
Model               object
Price                int64
Registered_City     object
Year               float64
dtype: object

In [179]:
new_df.columns

Index(['Brand', 'Condition', 'Fuel', 'KMs_Driven', 'Model', 'Price',
       'Registered_City', 'Year'],
      dtype='object')

In [194]:
brand_mode = new_df.Brand.mode()
brand_mode

0    Suzuki
Name: Brand, dtype: object

In [195]:
new_df["Brand"] = new_df.Brand.fillna(brand_mode)

In [180]:
brand_mode = new_df.Brand.mode()
brand_mode
new_df.Brand = new_df.Brand.fillna(brand_mode)

In [196]:
new_df.Brand.isnull().sum()

np.int64(2137)

In [181]:
condition_mode = new_df.Condition.mode()
condition_mode
new_df.Condition = new_df.Condition.fillna(condition_mode)

In [182]:
fuel_mode = new_df.Fuel.mode()
fuel_mode
new_df.Fuel = new_df.Fuel.fillna(fuel_mode)

In [183]:
kms_med = new_df.KMs_Driven.median()
kms_med
new_df.KMs_Driven = new_df.KMs_Driven.fillna(kms_med)

In [184]:
model_mode = new_df.Model.mode()
model_mode
new_df.Model = new_df.Model.fillna(model_mode)

In [185]:
reg_city_mode = new_df.Registered_City.mode()

reg_city_mode
new_df.Registered_City = new_df.Registered_City.fillna(reg_city_mode)

In [186]:
year_mode = new_df.Year.mode()
year_mode
new_df.Year = new_df.Year.fillna(year_mode)

In [187]:
new_df.columns

Index(['Brand', 'Condition', 'Fuel', 'KMs_Driven', 'Model', 'Price',
       'Registered_City', 'Year'],
      dtype='object')

In [188]:
new_df.head()

,Brand,Condition,Fuel,KMs_Driven,Model,Price,Registered_City,Year
0,Toyota,Used,Diesel,1.0,Prado,2100000,Karachi,1997.0
1,Suzuki,Used,Petrol,100000.0,Bolan,380000,Karachi,2006.0
2,Suzuki,Used,CNG,12345.0,Bolan,340000,Karachi,1998.0
3,Suzuki,Used,Petrol,94000.0,Alto,535000,Karachi,2010.0
4,Toyota,Used,Petrol,100000.0,Corolla XLI,1430000,Karachi,2013.0

In [189]:
new_df.isnull().sum()

Brand              2137
Condition          2136
Fuel               2445
KMs_Driven            0
Model              2448
Price                 0
Registered_City    4636
Year               2284
dtype: int64

In [190]:
df.isnull().sum()

Brand               2137
Condition           2136
Fuel                2445
KMs_Driven          2286
Model               2448
Price                  0
Registered_City     4636
Transaction_Type    2445
Year                2284
dtype: int64