In [69]:
import numpy as np
import pandas as pd

In [70]:
data = {
    "Name": ["Adam", "John", "Soha", "Zara", "Neha", "Laiba", "Zayan", "Abid", "Mariam", "Ahmed"],
    "Gender": ["Male", "Male", "Female", "Female", "Female", "Female", "Male", "Male", "Female", "Male"],
    "Study_Hours": [6, 4, 7, 2, 5, 4, 10, 7, 5, 6],
    "Result":["Pass", "Pass", "Pass", "Fail", "Fail", "Pass", "Pass", "Pass", "Fail", "Pass"]
    # "Grade": ["A", "B", "A", "C", "B", "C", "A", "B", "A", "A"],
    # "City": ["Karachi", "Lahore", "Karachi", "Islamabad", "Karachi","Karachi", "Lahore", "Karachi", "Islamabad", "Karachi"]
}
df = pd.DataFrame(data)
df

     Name  Gender  Study_Hours Result
0    Adam    Male            6   Pass
1    John    Male            4   Pass
2    Soha  Female            7   Pass
3    Zara  Female            2   Fail
4    Neha  Female            5   Fail
5   Laiba  Female            4   Pass
6   Zayan    Male           10   Pass
7    Abid    Male            7   Pass
8  Mariam  Female            5   Fail
9   Ahmed    Male            6   Pass

In [71]:
df["Gender"] = pd.get_dummies(df["Gender"], prefix="Gender", drop_first=True).astype(int)
df

     Name  Gender  Study_Hours Result
0    Adam       1            6   Pass
1    John       1            4   Pass
2    Soha       0            7   Pass
3    Zara       0            2   Fail
4    Neha       0            5   Fail
5   Laiba       0            4   Pass
6   Zayan       1           10   Pass
7    Abid       1            7   Pass
8  Mariam       0            5   Fail
9   Ahmed       1            6   Pass

In [ ]:
df["Result"] = pd.get_dummies(df["Result"], prefix="Result", drop_first=True).astype(int)
df

     Name  Gender  Study_Hours  Result
0    Adam       1            6       1
1    John       1            4       1
2    Soha       0            7       1
3    Zara       0            2       0
4    Neha       0            5       0
5   Laiba       0            4       1
6   Zayan       1           10       1
7    Abid       1            7       1
8  Mariam       0            5       0
9   Ahmed       1            6       1

In [73]:
x = df[["Gender","Study_Hours"]]
# x
y = df[["Result"]]
x

   Gender  Study_Hours
0       1            6
1       1            4
2       0            7
3       0            2
4       0            5
5       0            4
6       1           10
7       1            7
8       0            5
9       1            6

In [74]:
y

   Result
0       1
1       1
2       1
3       0
4       0
5       1
6       1
7       1
8       0
9       1

In [75]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
fs = SequentialFeatureSelector(lr, k_features=2, forward=True)
fs.fit(x,y)

TypeError: SequentialFeatureSelector.__init__() got an unexpected keyword argument 'k_features'