# ENCODING 
## What is Encoding?
At its core, encoding is about representing data using a specific system. This system ensures that the data can be correctly interpreted by the algorithm or system you’re using. Without encoding, your data could be meaningless or lead to incorrect results.

## Why is Encoding Important?
Machine Learning Algorithms: Many machine learning algorithms require numerical input. Data needs to be transformed into a numerical format (e.g., 0 to 1, or decimals) before they can be used in calculations.
Data Consistency: Encoding ensures consistent representation of data across different sources or systems.
Improved Performance: Properly encoding data can dramatically improve the performance of machine learning models.

In [20]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [21]:
data = {
    "ID": [101,102,103,104,105,106,107,108,109,110],
    "Name": ["Adam", "John", "Soha", "Zara", "Neha", "Laiba", "Zayan", "Abid", "Mariam", "Ahmed"],
    "Gender": ["Male", "Male", "Female", "Female", "Female", "Female", "Male", "Male", "Female", "Male"],
    "Course": ["Python", "Javascript", "Flutter", "Javascript", "Python", "Python", "Flutter", "Javascript", "Python", "Flutter"],
    "Grade": ["A", "B", "A", "C", "B", "C", "A", "B", "A", "A"],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", "Karachi","Karachi", "Lahore", "Karachi", "Islamabad", "Karachi"]
}
df = pd.DataFrame(data)
df

    ID    Name  Gender      Course Grade       City
0  101    Adam    Male      Python     A    Karachi
1  102    John    Male  Javascript     B     Lahore
2  103    Soha  Female     Flutter     A    Karachi
3  104    Zara  Female  Javascript     C  Islamabad
4  105    Neha  Female      Python     B    Karachi
5  106   Laiba  Female      Python     C    Karachi
6  107   Zayan    Male     Flutter     A     Lahore
7  108    Abid    Male  Javascript     B    Karachi
8  109  Mariam  Female      Python     A  Islamabad
9  110   Ahmed    Male     Flutter     A    Karachi

5. Encoding (for categorical data)
- Convert non-numeric features into numeric form.
- Techniques:
    1. Label Encoding (ordered categories).
    2. One-Hot / Dummy Variables (unordered).
    3. Binary Encoding (Yes/No → 1/0).

In [22]:
df["Gender"]

0      Male
1      Male
2    Female
3    Female
4    Female
5    Female
6      Male
7      Male
8    Female
9      Male
Name: Gender, dtype: object

In [25]:
df["Gender"] = df["Gender"].map({"Male":1, "Female":0})
df

    ID    Name  Gender      Course Grade       City
0  101    Adam       1      Python     A    Karachi
1  102    John       1  Javascript     B     Lahore
2  103    Soha       0     Flutter     A    Karachi
3  104    Zara       0  Javascript     C  Islamabad
4  105    Neha       0      Python     B    Karachi
5  106   Laiba       0      Python     C    Karachi
6  107   Zayan       1     Flutter     A     Lahore
7  108    Abid       1  Javascript     B    Karachi
8  109  Mariam       0      Python     A  Islamabad
9  110   Ahmed       1     Flutter     A    Karachi

In [23]:
# 2. Apply Label Encoding 
# encoded_data = pd.get_dummies(df['Gender'], prefix='Gender', drop_first=True).astype(int)
# encoded_data

In [24]:
# encoded_data