# FEATURE SCALING IN MACHINE LEARNING

###  What is Feature Scaling?
Feature scaling is the process of transforming or balancing the values of your features (the variables you use for your model) to a similar range. It essentially adjusts the scale of your data so that features with larger values don't dominate the model and vice versa.

### Common Feature Scaling Techniques
1. Standardization (Z-score Scaling)
2. Min-Max Scaling (Normalization)
3.	Robust Scaling
4.	Max Absolute Scaling

In [180]:
import pandas as pd

data = {
    "Name": ["Adam", "Neha", "Zoha", "John", "Zahid", "Basit", "Adeel"],
    "Age": [21,31,12,44,63,28, 25],
    "Salary" :[31000, 55000, 70000, 65000, 55000, 45000, 40000]

}
df = pd.DataFrame(data)
df

    Name  Age  Salary
0   Adam   21   31000
1   Neha   31   55000
2   Zoha   12   70000
3   John   44   65000
4  Zahid   63   55000
5  Basit   28   45000
6  Adeel   25   40000

In [181]:
df["Salary"]

0    31000
1    55000
2    70000
3    65000
4    55000
5    45000
6    40000
Name: Salary, dtype: int64

---

## 1. Standard Scaling
#### 1.	Standardization (Z-score Scaling): 
- a.	How it works: Transforms features to have a mean of 0 and a standard deviation of 1. x' = (x - mean) / std
- b.	Use Case: Often preferred because it doesn't require you to define a specific range. It focuses on the position of the data points, making it more robust to outliers.
- c.	Example: Commonly used for continuous features like age, income, or height.

In [182]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(df[["Salary"]])
ss.transform(df[["Salary"]])

array([[-1.60936554],
       [ 0.26822759],
       [ 1.4417233 ],
       [ 1.05055806],
       [ 0.26822759],
       [-0.51410288],
       [-0.90526812]])

In [183]:
new_df = pd.DataFrame(ss.transform(df[["Salary"]]))
new_df

          0
0 -1.609366
1  0.268228
2  1.441723
3  1.050558
4  0.268228
5 -0.514103
6 -0.905268

In [184]:
df["Salary_1"] = new_df[0]
df

    Name  Age  Salary  Salary_1
0   Adam   21   31000 -1.609366
1   Neha   31   55000  0.268228
2   Zoha   12   70000  1.441723
3   John   44   65000  1.050558
4  Zahid   63   55000  0.268228
5  Basit   28   45000 -0.514103
6  Adeel   25   40000 -0.905268

---

## 2. Normalization Scaling : (Min, Max)
#### 2.	Min-Max Scaling (Normalization): 
- a.	How it works: Scales features to a range between 0 and 1. x' = (x - min) / (max - min)
- b.	Use Case: When you want to preserve the original distribution of the data, and the data is relatively bounded. Good for algorithms that expect a particular range of values.
- c.	Example: Normalization is often used for images (pixel values) or data with a range of values.

In [185]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()
ms.fit(df[["Salary"]])
# ms.transform(df[["Salary"]])
new_df2 = pd.DataFrame(ms.transform(df[["Salary"]]))
new_df2

          0
0  0.000000
1  0.615385
2  1.000000
3  0.871795
4  0.615385
5  0.358974
6  0.230769

In [186]:
df["Salary_2"] = new_df2[0]
df

    Name  Age  Salary  Salary_1  Salary_2
0   Adam   21   31000 -1.609366  0.000000
1   Neha   31   55000  0.268228  0.615385
2   Zoha   12   70000  1.441723  1.000000
3   John   44   65000  1.050558  0.871795
4  Zahid   63   55000  0.268228  0.615385
5  Basit   28   45000 -0.514103  0.358974
6  Adeel   25   40000 -0.905268  0.230769

---

## 3. Robast Scaler


- a.	How it works: Scales features using the median and interquartile range (IQR). This is more robust to outliers than min-max scaling.
- b.	Use Case: When dealing with datasets that contain outliers that can significantly distort model results.

In [187]:
from sklearn.preprocessing import RobustScaler
rs = RobustScaler()
rs.fit(df[["Salary"]])
# ss.transform(df[["Salary"]])
new_df3 = pd.DataFrame(rs.transform(df[["Salary"]]))
df["Salary_3"] = new_df3[0]
df

    Name  Age  Salary  Salary_1  Salary_2  Salary_3
0   Adam   21   31000 -1.609366  0.000000 -1.371429
1   Neha   31   55000  0.268228  0.615385  0.000000
2   Zoha   12   70000  1.441723  1.000000  0.857143
3   John   44   65000  1.050558  0.871795  0.571429
4  Zahid   63   55000  0.268228  0.615385  0.000000
5  Basit   28   45000 -0.514103  0.358974 -0.571429
6  Adeel   25   40000 -0.905268  0.230769 -0.857143

## 4.	Max Absolute Scaling

- a.	How it works: Scales features by taking the absolute value of each element, and then dividing by the maximum absolute value.
- b.	Use Case: Similar to min-max but often works better with non-negative values, as it avoids artificially shrinking the range of values.

In [188]:
from sklearn.preprocessing import MaxAbsScaler
mas = MaxAbsScaler()
mas.fit(df[["Salary"]])
# ss.transform(df[["Salary"]])
new_df4 = pd.DataFrame(mas.transform(df[["Salary"]]))
df["Salary_4"] = new_df4[0]
df

    Name  Age  Salary  Salary_1  Salary_2  Salary_3  Salary_4
0   Adam   21   31000 -1.609366  0.000000 -1.371429  0.442857
1   Neha   31   55000  0.268228  0.615385  0.000000  0.785714
2   Zoha   12   70000  1.441723  1.000000  0.857143  1.000000
3   John   44   65000  1.050558  0.871795  0.571429  0.928571
4  Zahid   63   55000  0.268228  0.615385  0.000000  0.785714
5  Basit   28   45000 -0.514103  0.358974 -0.571429  0.642857
6  Adeel   25   40000 -0.905268  0.230769 -0.857143  0.571429

----------------------
---------------------

    Note: 
        1. Scaling can only be performed on Numeric Data
        2. After Scaling drop the original Column (non_scaled)